### ISSUE TITLE
Manifest doesn't recognize or emit media files for inherited templates.

### ISSUE THREAD

**Issue by aweber1** [Sitecore/jss#174]
## Description
Given the following manifest declarations:

```
export default function(manifest) {
  manifest.addTemplate({
    name: 'Car',
    fields: [
      { name: 'Model', type: CommonFieldTypes.SingleLineText },
      { name: 'Description', type: CommonFieldTypes.RichText },
      { name: 'Thumbnail', type: CommonFieldTypes.Image },
      { name: 'Image', type: CommonFieldTypes.Image },
      { name: 'Code', type: CommonFieldTypes.SingleLineText },
      { name: 'Power', type: CommonFieldTypes.SingleLineText },
      { name: 'Year', type: CommonFieldTypes.SingleLineText },
      { name: 'Features', type: CommonFieldTypes.RichText },
    ],
  });

  manifest.addComponent({
    name: 'CarTeaser',
    icon: SitecoreIcon.DocumentTag,
    inherits: ['Car']
  });
}
```
and corresponding component data:
```
- componentName: CarTeaser
    fields:
      Model: BMW 530xd
      Code: bmw
      Description: |
          The Volkswagen Passat is a large family car manufactured and marketed by Volkswagen since 1973, and now in its eighth generation.
      Thumbnail:
        src: /data/media/img/bmw.jpg
```

It is expected that the manifest would recognize the `/data/media/img/bmw.jpg` value provided for the `CarTeaser` component and copy that file to the `/sitecore/manifest` folder during manifest generation. The import process would then upload that file to the Sitecore media library during import.

However, the file is not recognized or copied to the manifest folder. And the import process then reports errors that the file can't be found.

The issue is that the `buildMediaOutput` function in [packages/sitecore-jss-manifest/src/generator/pipelines/generateMedia/utils.ts](https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-manifest/src/generator/pipelines/generateMedia/utils.ts) does resolve fields that a template may inherit, it only inspects fields that are directly assigned to a template. 

The solution is to resolve inherited templates/fields when building media output for the manifest.
