### ISSUE TITLE
Route items are not imported in a different language

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#53]
TP4

Scenario:
1. Create `da` language under `system/languages`
2. add `da.yml` for the Home route
3. "Translate" the route in Danish 😄 
```yml
id: home-page
fields:
  pageTitle: danish title
placeholders:
  jss-main:
  - componentName: ContentBlock
    fields:
      heading: danish heading
      content: danish content
```
4. Run `jss deploy items -c --language da`
5. Result: the component datasource item is created in `da` while the Home route item is created in `English` with Danish content.
