### ISSUE TITLE
Item Link treated differently in disconnected and connected modes

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#55]
I've got a custom component with an `ItemLink` field:
```javascript
manifest.addComponent({
  name: "MyComponent",
  icon: SitecoreIcon.DocumentMusic,
  fields: [
    {
      name: "myField",
      type: CommonFieldTypes.ItemLink
    }
  ]
});
```

I have the following route definition:
```yml
id: home-page
placeholders:
  jss-main:
    - componentName: MyComponent
      fields:
        myField:
          - id: some-other-item
```

When you reference this component in disconnected mode, you have to reference the `myField` field through an array (which is confusing since an item link shouldn't be represented as an array):
```javascript
this.props.fields.myField[0].fields.otherField.value
```

When you deploy this route to Sitecore and run this code, you get an error. Instead you must reference as follows in connected mode:
```javascript
this.props.fields.myField.fields.otherField.value
```

The issue is in the route definition. `myField` should actually be specified as follows:
```yml
myField: some-other-item
```

However I still expect the disconnected Layout Service to treat this field the same way it'll be treated after an import, even if my YAML is bad.
